$(function() {
  $( "#content-tabs" ).tabs(); 
  $( "#camere" ).accordion({
	collapsible: false,
	heightStyle: "content"
});
  $( "#contacttabs" ).accordion({
	collapsible: false,
	heightStyle: "content"
});
  $(".group1").colorbox({rel:'group1', transition:"none"});

  $('select[id="tip_search"]').change(function(){
	  var action = $(this).val();
	$("#top-search-form").attr("action", "/tip/" + action);
  });
  
   var availableTags = [
	  "Abrud",
	  "Adjud",
	  "Agnita",
	  "Aiud",
	  "Alba Iulia",
	  "Alesd",
	  "Alexandria",
	  "Amara",
	  "Anina",
	  "Aninoasa",
	  "Arad",
	  "Ardud",
	  "Avrig",
	  "Azuga",
	  "Babadag",
	  "Babeni",
	  "Bacau",
	  "Baia de Arama",
	  "Baia de Aries",
	  "Baia Mare",
	  "Baia Sprie",
	  "Baicoi",
	  "Baile Govora",
	  "Baile Herculane",
	  "Baile Olanesti",
	  "Baile Tusnad",
	  "Bailesti",
	  "Balan",
	  "Balcesti",
	  "Bals",
	  "Baneasa",
	  "Baraolt",
	  "Barlad",
	  "Bechet",
	  "Beclean",
	  "Beius",
	  "Berbesti",
	  "Beresti",
	  "Bicaz",
	  "Bistrita",
	  "Blaj",
	  "Bocsa",
	  "Boldesti-Scaeni",
	  "Bolintin-Vale",
	  "Borsa",
	  "Borsec",
	  "Botosani",
	  "Brad",
	  "Bragadiru",
	  "Braila",
	  "Brasov",
	  "Breaza",
	  "Brezoi",
	  "Brosteni",
	  "Bucecea",
	  "Bucuresti",
	  "Budesti",
	  "Buftea",
	  "Buhusi",
	  "Bumbesti-Jiu",
	  "Busteni",
	  "Buzau",
	  "Buzias",
	  "Cajvana",
	  "Calafat",
	  "Calan",
	  "Calarasi",
	  "Calimanesti",
	  "Campeni",
	  "Campia Turzii",
	  "Campina",
	  "Campulung Moldovenesc",
	  "Campulung",
	  "Caracal",
	  "Caransebes",
	  "Carei",
	  "Cavnic",
	  "Cazanesti",
	  "Cehu Silvaniei",
	  "Cernavoda",
	  "Chisineu-Cris",
	  "Chitila",
	  "Ciacova",
	  "Cisnadie",
	  "Cluj-Napoca",
	  "Codlea",
	  "Comanesti",
	  "Comarnic",
	  "Constanta",
	  "Copsa Mica",
	  "Corabia",
	  "Costesti",
	  "Covasna",
	  "Craiova",
	  "Cristuru Secuiesc",
	  "Cugir",
	  "Curtea de Arges",
	  "Curtici",
	  "Dabuleni",
	  "Darabani",
	  "Darmanesti",
	  "Dej",
	  "Deta",
	  "Deva",
	  "Dolhasca",
	  "Dorohoi",
	  "Draganesti-Olt",
	  "Dragasani",
	  "Dragomiresti",
	  "Drobeta-Turnu Severin",
	  "Dumbraveni",
	  "Eforie",
	  "Fagaras",
	  "Faget",
	  "Falticeni",
	  "Faurei",
	  "Fetesti",
	  "Fieni",
	  "Fierbinti-Targ",
	  "Filiasi",
	  "Flamanzi",
	  "Focsani",
	  "Frasin",
	  "Fundulea",
	  "Gaesti",
	  "Galati",
	  "Gataia",
	  "Geoagiu",
	  "Gheorgheni",
	  "Gherla",
	  "Ghimbav",
	  "Giurgiu",
	  "Gura Humorului",
	  "Harlau",
	  "Harsova",
	  "Hateg",
	  "Horezu",
	  "Huedin",
	  "Hunedoara",
	  "Husi",
	  "Ianca",
	  "Iasi",
	  "Iernut",
	  "Ineu",
	  "Insuratei",
	  "Intorsura Buzaului",
	  "Isaccea",
	  "Jibou",
	  "Jimbolia",
	  "Lehliu Gara",
	  "Lipova",
	  "Liteni",
	  "Livada",
	  "Ludus",
	  "Lugoj",
	  "Lupeni",
	  "Macin",
	  "Magurele",
	  "Mangalia",
	  "Marasesti",
	  "Marghita",
	  "Medgidia",
	  "Medias",
	  "Miercurea Ciuc",
	  "Miercurea Nirajului",
	  "Miercurea Sibiului",
	  "Mihailesti",
	  "Milisauti",
	  "Mioveni",
	  "Mizil",
	  "Moinesti",
	  "Moldova Noua",
	  "Moreni",
	  "Motru",
	  "Murfatlar",
	  "Murgeni",
	  "Nadlac",
	  "Nasaud",
	  "Navodari",
	  "Negresti",
	  "Negresti-Oas",
	  "Negru Voda",
	  "Nehoiu",
	  "Novaci",
	  "Nucet",
	  "Ocna Mures",
	  "Ocna Sibiului",
	  "Ocnele Mari",
	  "Odobesti",
	  "Odorheiu Secuiesc",
	  "Oltenita",
	  "Onesti",
	  "Oradea",
	  "Orastie",
	  "Oravita",
	  "Orsova",
	  "Otelu Rosu",
	  "Otopeni",
	  "Ovidiu",
	  "Panciu",
	  "Pancota",
	  "Pantelimon",
	  "Pascani",
	  "Patarlagele",
	  "Pecica",
	  "Petrila",
	  "Petrosani",
	  "Piatra Neamt",
	  "Piatra-Olt",
	  "Pitesti",
	  "Ploiesti",
	  "Plopeni",
	  "Podu Iloaiei",
	  "Pogoanele",
	  "Popesti-Leordeni",
	  "Potcoava",
	  "Predeal",
	  "Pucioasa",
	  "Racari",
	  "Radauti",
	  "Ramnicu Sarat",
	  "Rasnov",
	  "Recas",
	  "Reghin",
	  "Resita",
	  "Roman",
	  "Rosiorii de Vede",
	  "Rovinari",
	  "Roznov",
	  "Rupea",
	  "Sacele",
	  "Sacueni",
	  "Salcea",
	  "Saliste",
	  "Salistea de Sus",
	  "Salonta",
	  "Sangeorgiu de Padure",
	  "Sangeorz-Bai",
	  "Sannicolau Mare",
	  "Santana",
	  "Sarmasu",
	  "Satu Mare",
	  "Saveni",
	  "Scornicesti",
	  "Sebes",
	  "Sebis",
	  "Segarcea",
	  "Seini",
	  "Sfantu Gheorghe",
	  "Sibiu",
	  "Sighetu Marmatiei",
	  "Sighisoara",
	  "Simeria",
	  "simleu Silvaniei",
	  "Sinaia",
	  "Siret",
	  "Slanic",
	  "Slanic-Moldova",
	  "Slatina",
	  "Slobozia",
	  "Solca",
	  "somcuta Mare",
	  "Sovata",
	  "stefanesti, Arges",
	  "stefanesti, Botosani",
	  "stei",
	  "Strehaia",
	  "Suceava",
	  "Sulina",
	  "Talmaciu",
	  "tandarei",
	  "Targoviste",
	  "Targu Bujor",
	  "Targu Carbunesti",
	  "Targu Frumos",
	  "Targu Jiu",
	  "Targu Lapus",
	  "Targu Mures",
	  "Targu Neamt",
	  "Targu Ocna",
	  "Targu Secuiesc",
	  "Tarnaveni",
	  "Tasnad",
	  "Tautii-Magheraus",
	  "Techirghiol",
	  "Tecuci",
	  "Teius",
	  "ticleni",
	  "Timisoara",
	  "Tismana",
	  "Titu",
	  "Toplita",
	  "Topoloveni",
	  "Tulcea",
	  "Turceni",
	  "Turda",
	  "Turnu Magurele",
	  "Ulmeni",
	  "Ungheni",
	  "Uricani",
	  "Urlati",
	  "Urziceni",
	  "Valea lui Mihai",
	  "Valenii de Munte",
	  "Vanju Mare",
	  "Vascau",
	  "Vaslui",
	  "Vatra Dornei",
	  "Vicovu de Sus",
	  "Victoria",
	  "Videle",
	  "Viseu de Sus",
	  "Vlahita",
	  "Voluntari",
	  "Vulcan",
	  "Zalau",
	  "Zarnesti",
	  "Zimnicea",
	  "Zlatna"
	];
	$( "#select-oras" ).autocomplete({
	source: availableTags
	});
	$( "#oras" ).autocomplete({
	source: availableTags
	});
	$( "#oras2" ).autocomplete({
	source: availableTags
	});
  });